import turtle

fran = turtle.Turtle()
fran.width(5)

fran.forward(25)
fran.up()
fran.backward(25)
fran.left(90)
fran.down()
fran.forward(50)
fran.right(90)
fran.forward(50)
fran.up()
fran.backward(50)
fran.right(90)
fran.forward(50)
fran.down()
fran.forward(50)

fran.left(90)
fran.up()
fran.forward(75)
fran.down()
fran.forward(50)
fran.left(90)
fran.forward(50)
fran.left(90)
fran.forward(20)
fran.up()
fran.backward(20)
fran.right(90)
fran.backward(50)
fran.right(90)
fran.backward(50)
fran.left(90)
fran.down()
fran.forward(100)
fran.right(90)
fran.forward(50)


